unbind C-b
set -g prefix `
bind-key ` last-window
bind-key e send-prefix

set -g status-left ''
setw -g mode-keys vi
set -g status-position bottom
set -g status-right-length 50
set -g status-left-length 20

set-option -g history-limit 5000
